// <auto-generated />
using System;
using LEKSupply.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LEKSupply.Migrations
{
    [DbContext(typeof(LEKSupplyDbContext))]
    [Migration("20230730182231_add-novas-mercadorias")]
    partial class addnovasmercadorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LEKSupply.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("Data");

                    b.Property<int>("IdMercadoria")
                        .HasColumnType("int")
                        .HasColumnName("IdMercadoria");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Local");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("LEKSupply.Models.Mercadoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Fabricante");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Mercadoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "df95ef1a-e596-4647-8f9c-0d9ecd5cde99",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Mouse",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "ee4bdc3c-5008-4296-8dcc-900c2e0ab603",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Teclado",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "782c0f98-0b8e-421b-b97e-3a4ad474ae57",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Fone de ouvido",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "d0d168a2-fe3e-4ca6-b72b-6b2593abaf1f",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Camiseta",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "9b22dfa0-5915-4d9d-ad6e-f037f74b4e8d",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Bermuda",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "77afdde1-c198-447b-b4a7-dc1807b50a4e",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Blusa",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "de441cad-c74b-41df-ad84-8262953928ee",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Hasbro",
                            Nome = "Carrinho de corrrida",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "0d4807b9-4175-4eb3-a077-297e3ba85f20",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Hasbro",
                            Nome = "Boneco de ação",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "9fc5cf5c-6893-4dea-97fd-72ea5a47c120",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Hasbro",
                            Nome = "Casinha de brinquedo",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "5fbc6410-a651-49f8-accc-edb714752cff",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Lays",
                            Nome = "Batatatinhas",
                            Status = "A",
                            Tipo = "Alimentos"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "2efa1455-3775-4475-b405-922c63817b88",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Nestle",
                            Nome = "kit kat",
                            Status = "A",
                            Tipo = "Alimentos"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "7924e2b2-6008-48de-9c6d-30ec7158a33c",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Lacta",
                            Nome = "Sonho de Valsa",
                            Status = "A",
                            Tipo = "Alimentos"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "c9a3d3eb-a623-476b-ad52-a121b3697b96",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Philips",
                            Nome = "Lampada",
                            Status = "A",
                            Tipo = "Materiais de construção"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "9c785acf-ab08-44fd-9b3f-f6e9a2ef7bcd",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Pial",
                            Nome = "Tomada",
                            Status = "A",
                            Tipo = "Materiais de construção"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "894b23c3-834b-458c-98cc-8a3456aa4a1c",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Gabinete desktop",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "ee638f56-7250-413f-a020-80b2d654ca83",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Microfone",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "102ae8db-62c5-446a-a032-c572a7ad419c",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Monitor",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "057ae035-443e-404d-9467-e61d1b07aacd",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Processador intel",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "349d8196-d4cb-45d7-a727-3bc7e3e1206e",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Placa de video",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "023a9af9-60ef-4bc3-ad73-4b66f6c88492",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Casado",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "37d42d04-3e4a-417d-896a-2c49f107d4d4",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Calça jeans",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "82c5e39e-aa05-4d2e-a9b2-a9db82d48740",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Fashion Clothing",
                            Nome = "Camiseta Listrada",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "84449487-eab9-40ba-86be-6e276d40d8a1",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "TechCom",
                            Nome = "Smartphone Galaxy",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "6a9afac4-cb96-4d44-ace1-e72b8f5dd5d3",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "BrincaBem",
                            Nome = "Carrinho de Controle Remoto",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "f685cab9-db61-4522-a789-59af2f724041",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Saboroso Foods",
                            Nome = "Biscoitos Deliciosos",
                            Status = "A",
                            Tipo = "Alimentos"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "00f8ae5b-4899-4368-a2b2-f02059a1bd9b",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "CasaNova Supplies",
                            Nome = "Tinta para Parede",
                            Status = "A",
                            Tipo = "Materiais de construção"
                        },
                        new
                        {
                            Id = 27,
                            Codigo = "b070a959-8860-41ba-a709-6eaf605bd10d",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Fashion Deluxe",
                            Nome = "Jaqueta de Couro",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 28,
                            Codigo = "7fcaa9e7-8ec6-4170-83d2-5956a9cea554",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "TechGadgets",
                            Nome = "Smartwatch Fitness",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 29,
                            Codigo = "94987283-9cf5-4592-b3dc-cd9649eb0440",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "DivertKids",
                            Nome = "Quebra-Cabeça Colorido",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 30,
                            Codigo = "b99dfe53-e468-442b-9316-dad02cffd197",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "SweetTreats",
                            Nome = "Chocolate Cremoso",
                            Status = "A",
                            Tipo = "Alimentos"
                        });
                });

            modelBuilder.Entity("LEKSupply.Models.Saida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("Data");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("int")
                        .HasColumnName("IdEntrada");

                    b.Property<int?>("IdMercadoria")
                        .HasColumnType("int")
                        .HasColumnName("IdMercadoria");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Local");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Saida");
                });
#pragma warning restore 612, 618
        }
    }
}
