// <auto-generated />
using System;
using LEKSupply.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LEKSupply.Migrations
{
    [DbContext(typeof(LEKSupplyDbContext))]
    partial class LEKSupplyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LEKSupply.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("Data");

                    b.Property<int>("IdMercadoria")
                        .HasColumnType("int")
                        .HasColumnName("IdMercadoria");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Local");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("LEKSupply.Models.Mercadoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Fabricante");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Mercadoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "fec3355a-a6d9-48cf-a0d6-1dd28e9ae26f",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Mouse",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "bf551478-2cc6-4f2e-b4a1-15fca0311cca",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Teclado",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "3d089885-e41f-4504-a8b2-fec6f18c9e19",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Fone de ouvido",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "5a46da48-abc4-4e49-82bd-ef922d66e608",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Camiseta",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "61bd18c0-bd86-4dec-858e-eac8c281f6bb",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Bermuda",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "1faa9222-1bf6-4fb0-9b8e-f6f97aa52db2",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Blusa",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "db5c069f-e816-4577-8f28-3f4492813ed7",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Hasbro",
                            Nome = "Carrinho de corrrida",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "d6ccbfc1-11be-422a-b6cc-f1f7e38631e6",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Hasbro",
                            Nome = "Boneco de ação",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "4b745d70-bfd0-42f8-9f56-2584fa253d61",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Hasbro",
                            Nome = "Casinha de brinquedo",
                            Status = "A",
                            Tipo = "Brinquedos"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "1cd7dcd2-4205-4cb7-810d-9a814d46a747",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Lays",
                            Nome = "Batatatinhas",
                            Status = "A",
                            Tipo = "Alimentos"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "9364137a-8f25-4265-85cb-f4e417c40210",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Nestle",
                            Nome = "kit kat",
                            Status = "A",
                            Tipo = "Alimentos"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "a406cafe-afa4-4b14-9502-5a8ddfc70c6c",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Lacta",
                            Nome = "Sonho de Valsa",
                            Status = "A",
                            Tipo = "Alimentos"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "02d3d52d-95bc-43ee-a4d1-df2d476ae786",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Philips",
                            Nome = "Lampada",
                            Status = "A",
                            Tipo = "Materiais de construção"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "8e68869d-b349-4989-804e-944c7cc5e084",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Pial",
                            Nome = "Tomada",
                            Status = "A",
                            Tipo = "Materiais de construção"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "1ac1de3b-22c6-4566-b05a-577375d2f49c",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Gabinete desktop",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "82006ad0-b9c6-40bb-bc6f-b4e0a02645df",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Microfone",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "1c18de2d-d3e2-41d9-8c65-e74781505c16",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Monitor",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "16705546-d645-4942-9b87-48b2e29cc733",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Processador intel",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "b97a1305-0288-4792-9bf1-13133daa9965",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Dell",
                            Nome = "Placa de video",
                            Status = "A",
                            Tipo = "Eletrônicos"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "c083bc88-7a85-4477-bad0-5a32095307bd",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Casado",
                            Status = "A",
                            Tipo = "Roupas"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "3ee1c17e-e893-470e-bb78-c5da55ee59f5",
                            Descricao = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt ultricies congue. ",
                            Fabricante = "Leader",
                            Nome = "Calça jeans",
                            Status = "A",
                            Tipo = "Roupas"
                        });
                });

            modelBuilder.Entity("LEKSupply.Models.Saida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Data")
                        .HasColumnType("longtext")
                        .HasColumnName("Data");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("int")
                        .HasColumnName("IdEntrada");

                    b.Property<int?>("IdMercadoria")
                        .HasColumnType("int")
                        .HasColumnName("IdMercadoria");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Local");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Saida");
                });
#pragma warning restore 612, 618
        }
    }
}
